import type { CampusLocation } from "../types";

/**
 * University of Ibadan campus dataset for the MVP.
 * KDL uses a published coordinate. Other points are approximate
 * campus-area positions so the map works. Replace lat/lng by
 * long-pressing each place in Google Maps or OpenStreetMap
 * while you are on campus. Set coordsVerified to true after that.
 *
 * Campus centre used for the default map view: 7.4431, 3.9003
 */
export const CAMPUS_CENTER = { lat: 7.4431, lng: 3.9003 };

export const campusLocations: CampusLocation[] = [
  {
    id: "premier-gate",
    name: "Premier Gate (UI Gate)",
    description: "Main public entrance to the University of Ibadan campus.",
    latitude: 7.4412,
    longitude: 3.9086,
    category: "Gate",
    building: "Campus entrance",
    landmarks: ["Sango-UI Road", "Security post"],
    coordsVerified: false,
  },
  {
    id: "kdl",
    name: "Kenneth Dike Library",
    description: "Central university library beside the Faculty of Arts. Students call it KDL.",
    latitude: 7.44665,
    longitude: 3.89612,
    category: "Library",
    building: "Kenneth Dike Library",
    landmarks: ["Faculty of Arts", "Bookshop"],
    coordsVerified: true,
  },
  {
    id: "bookshop",
    name: "University Bookshop",
    description: "Campus bookshop near the central administration area.",
    latitude: 7.4448,
    longitude: 3.8994,
    category: "Admin",
    building: "Bookshop",
    landmarks: ["Trenchard Hall", "Senate Building"],
    coordsVerified: false,
  },
  {
    id: "trenchard",
    name: "Trenchard Hall",
    description: "Ceremonial hall in the central administration court.",
    latitude: 7.4444,
    longitude: 3.899,
    category: "Admin",
    building: "Trenchard Hall",
    landmarks: ["Senate Building", "University Court"],
    coordsVerified: false,
  },
  {
    id: "senate",
    name: "Senate Building",
    description: "Central administration and Senate chambers.",
    latitude: 7.4446,
    longitude: 3.8986,
    category: "Admin",
    building: "Senate Building",
    landmarks: ["Trenchard Hall", "Bookshop"],
    coordsVerified: false,
  },
  {
    id: "students-affairs",
    name: "Students Affairs",
    description: "Student services and related administrative offices.",
    latitude: 7.4452,
    longitude: 3.8982,
    category: "Admin",
    building: "Students Affairs building",
    landmarks: ["Admissions", "SUB"],
    coordsVerified: false,
  },
  {
    id: "admissions",
    name: "Admissions Office",
    description: "Registration and admissions offices used heavily by new students.",
    latitude: 7.4454,
    longitude: 3.8978,
    category: "Admin",
    building: "Admissions / Establishments",
    landmarks: ["Students Affairs", "Faculty of Arts"],
    coordsVerified: false,
  },
  {
    id: "faculty-arts",
    name: "Faculty of Arts",
    description: "Faculty of Arts complex near Kenneth Dike Library.",
    latitude: 7.4462,
    longitude: 3.8966,
    category: "Faculty",
    building: "Faculty of Arts",
    landmarks: ["Kenneth Dike Library", "Theatre Arts"],
    coordsVerified: false,
  },
  {
    id: "jaja",
    name: "Jaja Clinic",
    description: "University health centre on Jaja Avenue. First stop for many medical registrations.",
    latitude: 7.4428,
    longitude: 3.8975,
    category: "Health",
    building: "Jaja",
    landmarks: ["Jaja Avenue", "Halls of residence"],
    coordsVerified: false,
  },
  {
    id: "sub",
    name: "Student Union Building (SUB)",
    description: "Student union and student activity complex.",
    latitude: 7.445,
    longitude: 3.8972,
    category: "Food",
    building: "SUB / SGB",
    landmarks: ["Shopping complex", "Students Affairs"],
    coordsVerified: false,
  },
  {
    id: "chapel",
    name: "Chapel of the Resurrection",
    description: "Campus chapel and fellowship meeting point along Chapel Road.",
    latitude: 7.4468,
    longitude: 3.8988,
    category: "Worship",
    building: "Chapel",
    landmarks: ["Chapel Road", "Chapel tarmac"],
    coordsVerified: false,
  },
  {
    id: "mosque",
    name: "University Mosque",
    description: "Central mosque on campus.",
    latitude: 7.4422,
    longitude: 3.9015,
    category: "Worship",
    building: "Mosque",
    landmarks: ["Campus roads"],
    coordsVerified: false,
  },
  {
    id: "ict",
    name: "ICT / MIS Centre",
    description: "ICT and management information systems area in the central park.",
    latitude: 7.4456,
    longitude: 3.8988,
    category: "ICT",
    building: "ICT / MIS",
    landmarks: ["Administrative block", "Park"],
    coordsVerified: false,
  },
  {
    id: "tedder",
    name: "Tedder Hall",
    description: "Hall of residence in the central residential area.",
    latitude: 7.4436,
    longitude: 3.9008,
    category: "Hall",
    building: "Tedder Hall",
    landmarks: ["Mellanby Hall", "University Court"],
    coordsVerified: false,
  },
  {
    id: "mellanby",
    name: "Mellanby Hall",
    description: "Hall of residence near Tedder Hall.",
    latitude: 7.4432,
    longitude: 3.9014,
    category: "Hall",
    building: "Mellanby Hall",
    landmarks: ["Tedder Hall", "Kuti Hall"],
    coordsVerified: false,
  },
  {
    id: "kuti",
    name: "Kuti Hall",
    description: "Ransom Kuti Hall of residence.",
    latitude: 7.4426,
    longitude: 3.902,
    category: "Hall",
    building: "Kuti Hall",
    landmarks: ["Sultan Bello Hall", "Mellanby Hall"],
    coordsVerified: false,
  },
  {
    id: "bello",
    name: "Sultan Bello Hall",
    description: "Hall of residence near Kuti Hall.",
    latitude: 7.4424,
    longitude: 3.9026,
    category: "Hall",
    building: "Sultan Bello Hall",
    landmarks: ["Kuti Hall", "Independence Hall"],
    coordsVerified: false,
  },
  {
    id: "independence",
    name: "Independence Hall",
    description: "Independence Hall (Indy) of residence.",
    latitude: 7.4418,
    longitude: 3.9034,
    category: "Hall",
    building: "Independence Hall",
    landmarks: ["Nnamdi Azikiwe Hall"],
    coordsVerified: false,
  },
  {
    id: "zik",
    name: "Nnamdi Azikiwe Hall",
    description: "Zik Hall of residence.",
    latitude: 7.4415,
    longitude: 3.904,
    category: "Hall",
    building: "Nnamdi Azikiwe Hall",
    landmarks: ["Independence Hall"],
    coordsVerified: false,
  },
  {
    id: "qe",
    name: "Queen Elizabeth Hall",
    description: "Female hall of residence near the central court.",
    latitude: 7.444,
    longitude: 3.9012,
    category: "Hall",
    building: "Queen Elizabeth Hall",
    landmarks: ["University Court South"],
    coordsVerified: false,
  },
];

export const categories = [
  "All",
  "Gate",
  "Admin",
  "Library",
  "Health",
  "Worship",
  "Food",
  "Hall",
  "Faculty",
  "ICT",
] as const;
